import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Freenoo',
  description: 'Privacy Policy for Freenoo — Free Online PDF Tools',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ background: 'var(--bg)', color: 'var(--text)' }}>
      <header style={{ background: 'rgba(28,28,28,0.92)', borderBottom: '1px solid var(--border)' }}>
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/"><img src="/logo.png" alt="Freenoo" style={{ height: '40px', width: 'auto' }} /></Link>
          <Link href="/" className="text-sm" style={{ color: 'var(--text-muted)' }}>← Back to Home</Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2" style={{ color: 'var(--text)' }}>Privacy Policy</h1>
          <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Last updated: March 19, 2026</p>
        </div>

        <div style={{ lineHeight: '1.8' }}>
          <p className="mb-6 text-sm" style={{ color: 'var(--text-muted)' }}>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <S title="Interpretation and Definitions">
            <SS title="Interpretation">
              <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            </SS>
            <SS title="Definitions">
              <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>For the purposes of this Privacy Policy:</p>
              <BL items={[
                '<strong style="color:#fff">Account</strong> means a unique account created for You to access our Service or parts of our Service.',
                '<strong style="color:#fff">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                '<strong style="color:#fff">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to freenoo.',
                '<strong style="color:#fff">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website.',
                '<strong style="color:#fff">Country</strong> refers to: Uttarakhand, India',
                '<strong style="color:#fff">Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
                '<strong style="color:#fff">Personal Data</strong> is any information that relates to an identified or identifiable individual.',
                '<strong style="color:#fff">Service</strong> refers to the Website.',
                '<strong style="color:#fff">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.',
                '<strong style="color:#fff">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
                '<strong style="color:#fff">Website</strong> refers to freenoo, accessible from https://www.freenoo.com/',
                '<strong style="color:#fff">You</strong> means the individual accessing or using the Service.',
              ]} />
            </SS>
          </S>

          <S title="Collecting and Using Your Personal Data">
            <SS title="Personal Data">
              <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>While using Our Service, We may ask You to provide Us with certain personally identifiable information. This may include, but is not limited to:</p>
              <BL items={['Email address']} />
            </SS>
            <SS title="Usage Data">
              <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            </SS>
            <SS title="Tracking Technologies and Cookies">
              <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>We use Cookies and similar tracking technologies to track the activity on Our Service. The technologies We use may include:</p>
              <BL items={[
                '<strong style="color:#fff">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies.',
                '<strong style="color:#fff">Web Beacons.</strong> Certain sections of our Service may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages.',
              ]} />
              <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>We use both Session and Persistent Cookies for the purposes set out below:</p>
              <BL items={[
                '<strong style="color:#fff">Necessary / Essential Cookies</strong> — Essential to provide You with services available through the Website.',
                '<strong style="color:#fff">Cookies Policy / Notice Acceptance Cookies</strong> — Identify if users have accepted the use of cookies on the Website.',
                '<strong style="color:#fff">Functionality Cookies</strong> — Allow Us to remember choices You make when You use the Website.',
              ]} />
            </SS>
            <SS title="Use of Your Personal Data">
              <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>The Company may use Personal Data for the following purposes:</p>
              <BL items={[
                'To provide and maintain our Service, including to monitor the usage of our Service.',
                'To manage Your Account and registration as a user of the Service.',
                'For the performance of a contract.',
                'To contact You by email or other forms of electronic communication.',
                'To provide You with news, special offers, and general information about other goods and services.',
                'To manage Your requests to Us.',
                'For business transfers.',
                'For other purposes such as data analysis and identifying usage trends.',
              ]} />
            </SS>
            <SS title="Sharing Your Personal Data">
              <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>We may share Your Personal Data in the following situations:</p>
              <BL items={[
                '<strong style="color:#fff">With Service Providers</strong> to monitor and analyze the use of our Service.',
                '<strong style="color:#fff">For business transfers</strong> in connection with any merger, sale of Company assets, or acquisition.',
                '<strong style="color:#fff">With Affiliates</strong> who are required to honor this Privacy Policy.',
                '<strong style="color:#fff">With business partners</strong> to offer You certain products, services or promotions.',
                '<strong style="color:#fff">With Your consent</strong> for any other purpose.',
              ]} />
            </SS>
          </S>

          <S title="Retention of Your Personal Data">
            <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We apply different retention periods based on the purpose of processing:</p>
            <BL items={[
              '<strong style="color:#fff">User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.',
              '<strong style="color:#fff">Support tickets and correspondence:</strong> up to 24 months from the date of ticket closure.',
              '<strong style="color:#fff">Website analytics data:</strong> up to 24 months from the date of collection.',
              '<strong style="color:#fff">Server logs:</strong> up to 24 months for security monitoring and troubleshooting.',
            ]} />
          </S>

          <S title="Transfer of Your Personal Data">
            <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>
          </S>

          <S title="Delete Your Personal Data">
            <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account or by contacting Us. Please note that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
          </S>

          <S title="Disclosure of Your Personal Data">
            <SS title="Business Transactions">
              <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred.</p>
            </SS>
            <SS title="Law Enforcement">
              <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
            </SS>
            <SS title="Other Legal Requirements">
              <BL items={[
                'Comply with a legal obligation',
                'Protect and defend the rights or property of the Company',
                'Prevent or investigate possible wrongdoing in connection with the Service',
                'Protect the personal safety of Users of the Service or the public',
                'Protect against legal liability',
              ]} />
            </SS>
          </S>

          <S title="Security of Your Personal Data">
            <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </S>

          <S title="Children's Privacy">
            <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
          </S>

          <S title="Links to Other Websites">
            <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          </S>

          <S title="Changes to this Privacy Policy">
            <p className="text-sm mb-3" style={{ color: 'var(--text-muted)' }}>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.</p>
          </S>

          <S title="Contact Us">
            <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>If you have any questions about this Privacy Policy, You can contact us:</p>
            <BL items={['By email: <a href="mailto:freenoo@zohomail.in" style="color:#eb1000">freenoo@zohomail.in</a>']} />
          </S>
        </div>
      </main>

      <footer style={{ borderTop: '1px solid var(--border)', marginTop: '48px' }}>
        <div className="max-w-4xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <Link href="/"><img src="/logo.png" alt="Freenoo" style={{ height: '32px', width: 'auto' }} /></Link>
          <div className="flex items-center gap-4 text-xs" style={{ color: 'var(--text-muted)' }}>
            <Link href="/privacy" style={{ color: 'var(--accent)' }}>Privacy Policy</Link>
            <Link href="/terms" style={{ color: 'var(--text-muted)' }}>Terms & Conditions</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function S({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-8">
      <h2 className="text-xl font-bold mb-3" style={{ color: 'var(--text)', borderBottom: '1px solid var(--border)', paddingBottom: '8px' }}>{title}</h2>
      {children}
    </div>
  );
}

function SS({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-4 mb-2">
      <h3 className="text-base font-semibold mb-2" style={{ color: 'var(--text)' }}>{title}</h3>
      {children}
    </div>
  );
}

function BL({ items }: { items: string[] }) {
  return (
    <ul className="mt-2 mb-4 space-y-2 pl-2">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2 text-sm" style={{ color: 'var(--text-muted)' }}>
          <span style={{ color: 'var(--accent)', flexShrink: 0, marginTop: '2px' }}>•</span>
          <span dangerouslySetInnerHTML={{ __html: item }} />
        </li>
      ))}
    </ul>
  );
}
